WITH EARNINGS AS(
    SELECT (SALARY * MONTHS) AS TOTAL_EARNINGS,
    EMPLOYEE_ID
    FROM EMPLOYEE
)    
SELECT MAX(TOTAL_EARNINGS), 
COUNT(TOTAL_EARNINGS)
FROM EARNINGS
WHERE TOTAL_EARNINGS = (SELECT MAX(TOTAL_EARNINGS) FROM EARNINGS)
